@startuml
title Datenmodell – EliteGärtner


skinparam ranksep 70

class Match {
   +count : Int
   +matchedDate : Date     
}

class User {
    +userId : Int 
    +userName : String 
    +firstName : String 
    +lastName : String 
    +eMail : String 
    +passwordHash : String 
    +profileText : String 
}

class Preferences {
    +preferencesID : Int 
    +dateUpdated : Date 
}

class Tags {
    +tagId : Int
    +label : String
}

class HarvestUpload {
    +uploadId : Int 
    +userId : int 
    +ImageUrl : String 
    +Description: String 
    +WeightKg : float 
    +quantity : Int 
    +uploadDate : Date 
}

class Rating {
    +ratingId : Int
}

class Report {
  +reportId : Int
  +reason : String
  +reportDate : Date
}

class LeaderboardEntry {
  +entryId : Int
  +rank : Int
  +points : Int
  +period : String // Woche, Monat, etc.
}



'--- Beziehungen ---

User "1" -- "*" LeaderboardEntry : hat Rang
User "1" -- "1" Preferences : wählt/hat
User "1" -- "*" HarvestUpload : erstellt
User "1" -- "*" Report : erstellt
User -- Match : hat

Preferences "*" -- "*" Tags : enthalten

HarvestUpload "*" -- "*" Tags : enthalten
HarvestUpload "1" -- "*" Report : enthalten
HarvestUpload "n" -- "1" Rating : wählt aus
User "n" -- "1" Rating : wählt aus










@enduml