@startuml
skinparam componentStyle rectangle
skinparam shadowing false

' PRESENTATION LAYER
rectangle "Presentation Layer" #DDDDFF {
    component BlazorComponents as Blazor
    interface IAppLogic
    Blazor --> IAppLogic
}

' LOGIC
rectangle "Logic" #DDFFDD {
    IAppLogic -- AppLogic

    interface UploadService
    interface IHarvestDBSSuggestion
    interface IUserSuggestion
    interface IProfileMgm
    interface ILeaderboard

    component AppLogic {
        AppLogic --> UploadService
        AppLogic --> IHarvestDBSSuggestion
        AppLogic --> IUserSuggestion
        AppLogic --> IProfileMgm
        AppLogic --> ILeaderboard
    }

    component "Harvest Upload" as hUpload {
        UploadService -- hUpload
    }

    component "HarvestSuggestion" as HSugg {
        IHarvestDBSSuggestion -- HSugg
    }

    component "User Suggestion" as UserSugg {
        IUserSuggestion -- UserSugg
    }

    component "ProfileManagment" as PM {
        IProfileMgm -- PM
    }
    
    component Leaderboard
    
    ILeaderboard -- Leaderboard
    
}

' INFRASTRUCTURE LAYER
rectangle "Infrastructure" #CCEEFF {
    component Databasemanagement as DBM
    interface IPreferencesDBS
    interface IUploadDBS
    interface IHarvestDBS
    interface IUserDBS
    interface IProfilDBS

    IPreferencesDBS -- DBM
    IUploadDBS -- DBM
    IHarvestDBS -- DBM
    IUserDBS -- DBM
    IProfilDBS -- DBM
    Leaderboard -- ILeaderboardDBS
}

hUpload --> IUploadDBS
HSugg --> IHarvestDBS
HSugg -> UserSugg
UserSugg --> IUserDBS
UserSugg --> IPreferencesDBS
PM --> IPreferencesDBS
PM --> IProfilDBS
ILeaderboardDBS --> DBM

@enduml
