@startuml
left to right direction
skinparam componentStyle rectangle

package "PresentationLayer" {
  [Blazor Pages/Components] as UI
  [State/Session/Shared] as State
}

package "AppLogic" {
    [IHarvestSuggestion] as IHarvestSuggestion
    [ILeaderBoardService] as ILeaderBoardService
    [IMatchManager] as IMatchManager
    [IProfileMgm] as IProfileMgm 
    [IProfileSuggestion] as IProfileSuggestion
    [IUploadService] as IUploadService 
    [MatchManager] as MatchManager 
    [ProfileSuggestion] as ProfileSuggestion 
    [HarvestSuggestion] as HarvestSuggestion
    [ProfileMgm] as ProfileMgm 
    [UploadServiceImpl] as UploadServiceImpl 
    [LeaderBoardService] as LeaderBoardService 
}

package "DataManagement" {
    [ILeaderBoardDbs] as ILeaderBoardDbs
    [IMatchesDbs] as IMatchesDbs
    [IHarvestDbs] as IHarvestDbs
    [IProfileDbs] as IProfileDbs
    [ProfileDbs] as ProfileDbs
    [HarvestDbs] as HarvestDbs
    [MatchesDbs] as MatchesDbs
    [LeaderboardDbs] as LeaderboardDbs
    [EliteGaertnerDbContext] as DbContext
}



package "Contracts" {
    [DTOs] as DTOs
    [Enums] as Enums
}


package "PostgreSQL Docker Container"{
    [Seed] as Seed
    [Test-Seed] as TestSeed 
    database "Produktiv-Datenbank" as PD
    database "Test-Datenbank" as TD 
}

package "Tests"{
    [UnitTests] as UnitTests 
    [IntegrationsTests] as IT
}


UI -> State
UI ---> IProfileSuggestion
UI ---> IProfileMgm
UI ---> IUploadService
UI ---> IMatchManager
UI ---> ILeaderBoardService
UI ---> IHarvestSuggestion

IProfileMgm --> ProfileMgm
IProfileSuggestion --> ProfileSuggestion
IMatchManager --> MatchManager
IUploadService --> UploadServiceImpl 
ILeaderBoardService --> LeaderBoardService
IHarvestSuggestion --> HarvestSuggestion

MatchManager --> IHarvestDbs
MatchManager --> IProfileDbs
MatchManager --> IMatchesDbs
HarvestSuggestion --> IHarvestDbs
ProfileSuggestion --> IHarvestDbs 
ProfileSuggestion --> IProfileDbs 
ProfileSuggestion --> IMatchesDbs 
ProfileMgm --> IHarvestDbs
ProfileMgm --> IProfileDbs
LeaderBoardService --> ILeaderBoardDbs
UploadServiceImpl --> IHarvestDbs



IProfileDbs --> ProfileDbs
IHarvestDbs --> HarvestDbs
IMatchesDbs --> MatchesDbs
ILeaderBoardDbs --> LeaderboardDbs 


ProfileDbs --> DbContext
HarvestDbs --> DbContext
MatchesDbs --> DbContext
LeaderboardDbs --> DbContext



AppLogic ..> Contracts
DataManagement ..> Contracts
PresentationLayer ..> Contracts

DbContext --> PD
PD --> Seed
TD --> TestSeed

IT --> TD

@enduml